# Generated by Django 2.2.7 on 2019-11-26 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_income_category',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='is_income_category',
        ),
        migrations.AddField(
            model_name='category',
            name='expense_or_income_choices',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=9, verbose_name='Expense or income'),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='expense_or_income_choices',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=9, verbose_name='Expense or income'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 441134, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 441134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 442134, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 442134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 443133, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 443133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 442134, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 13, 24, 52, 442134, tzinfo=utc)),
        ),
    ]
