# Generated by Django 2.2.7 on 2019-11-26 16:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money_tracker', '0002_auto_20191126_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_or_income_choices', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=9, verbose_name='Expense or income')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 7, 1, 655630, tzinfo=utc), editable=False)),
                ('modified', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 7, 1, 655630, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 7, 1, 655630, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 7, 1, 655630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 7, 1, 655630, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 7, 1, 655630, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money_tracker.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money_tracker.UserCategory', verbose_name='User category'),
        ),
    ]
