# Generated by Django 2.2.7 on 2019-11-27 15:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money_tracker', '0004_auto_20191126_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_category',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 15, 17, 47, 52300, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 15, 17, 47, 52300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 15, 17, 47, 53300, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 15, 17, 47, 53300, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
