# Generated by Django 2.2.7 on 2019-12-04 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0005_auto_20191127_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Currency name')),
                ('symbol', models.CharField(max_length=16, verbose_name='Currency symbol')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 0, 11, 540296, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='expense_or_income_choices',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=9, verbose_name='Category type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 0, 11, 540296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 0, 11, 540296, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 0, 11, 540296, tzinfo=utc)),
        ),
    ]
