# Generated by Django 2.2.7 on 2019-11-26 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 37, 50, 387362, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 37, 50, 387362, tzinfo=utc)),
        ),
    ]
