# Generated by Django 2.2.7 on 2019-11-26 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191126_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 21, 27, 757618, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 16, 21, 27, 757618, tzinfo=utc)),
        ),
    ]
