# Generated by Django 2.2.7 on 2019-12-04 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0006_auto_20191204_1400'),
        ('accounts', '0006_auto_20191127_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='money_tracker.Currency'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 0, 11, 540296, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 0, 11, 540296, tzinfo=utc)),
        ),
    ]
